### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by estherkim** [ampproject/cdn-configuration#27]
- [x] Migrate `client-side-experiments-config.json` from ampproject/amphtml to this repo and switch the Google CDN to sync from this repo instead (est. Jan 7)
- [x] Create GitHub action workflows, verify scheduling works and that workflows correctly trigger any downstream/followup workflows (e.g., cherry pick triggers relevant promotions) (est. Jan 14)
- [x] Cloudflare CDN syncs changes (est. Jan 14)
- [x] Connect release workflows from GH to Google CDN (i.e., changes to `nightly` and `amp-release-*` branches auto-triggers a build inside Google systems) (est. Feb 4)
- [x] Connect promote workflows to Google CDN (i.e., changes to versions.json auto-triggers a promote workflow inside Google systems) (est. Feb 11)
- [x] Release-on-duty adoption (est. starting Feb 14)

Note: this issue does not deal with Cloudflare CDN server milestones

**Comment by danielrozenberg** [comment]
> Migrate client-side-experiments-config.json from ampproject/amphtml to this repo and switch the Google CDN to sync from this repo instead (est. Jan 7)

Tested this today and fixed a couple of minor issues. Glad to report that this is done and working!

**Comment by danielrozenberg** [comment]
>  Cloudflare CDN syncs changes (est. Jan 14)

Verified 🥳

**Comment by danielrozenberg** [comment]
>  Connect release workflows from GH to Google CDN (i.e., changes to nightly and amp-release-* branches auto-triggers a build inside Google systems) (est. Feb 4)

Verified 🥳🥳🥳

**Comment by danielrozenberg** [comment]
>  Connect promote workflows to Google CDN (i.e., changes to versions.json auto-triggers a promote workflow inside Google systems) (est. Feb 11)

Verified 🥳🥳🥳🥳

**Comment by danielrozenberg** [comment]
🥳🥳🥳🥳🥳
